version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd1234
      POSTGRES_DB: pulsedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pulsedb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
